### ISSUE TITLE
Несколько сайтов на одной ноде?

### ISSUE THREAD

**Issue by rasperepodvipodvert** [bitrixdock/production-single-node#2]
Подскажите как правильно сделать несколько сайтов с битриксом на одной ноде?

**Comment by igogorevi4** [comment]
нужно для каждого код положить в отдельную директорию, например:
/var/www/1site.ru
/var/www/2site.ru
...
/var/www/99site.ru

для каждого сделать свой отдельный docker-compose, в котором будут отличаться порты хостовой машины, в volumes прописать нужный пусть к коду (например, /var/www/1site.ru), container_name сделать всем свои (например, site1-php56-fpm)

в networks поменять site на, например, site1, чтобы у каждого проекта была своя изолированная сеть

и запускать с указанием файла:
docker-compose -f docker-compose-site1.yml up -d

**Comment by rasperepodvipodvert** [comment]
Thanks!
